import os

ROOT = os.getcwd()
UTILS = os.path.join('..', 'utils')

DATA_ROOT = os.path.join(ROOT, 'PubmedOA_MEDLINE_XML')
MEDLINE_ROOT = os.path.join(DATA_ROOT, 'MEDLINE')
PUBMEDOA_ROOT = os.path.join(DATA_ROOT, 'PubmedOA')
BIOLEMMATIZER_PATH = os.path.abspath(os.path.join(UTILS, 'biolemmatizer-core-1.2-jar-with-dependencies.jar'))

CONSOLIDATED_RAW_TEXT = os.path.join(ROOT, 'CONSOLIDATED_RAW_TEXT.txt')
CONSOLIDATED_SENTENCE_TEXT = os.path.join(ROOT, 'CONSOLIDATED_SENTENCE_TEXT.txt')
CONSOLIDATED_WORDS_TEXT = os.path.join(ROOT, 'CONSOLIDATED_WORDS_TEXT.txt')
CONSOLIDATED_PROCSESED_SENTENCE_TEXT = os.path.join(ROOT, 'PROCSESED_SENTENCE_TEXT.txt')
LEMMATIZED_WORDS_TEXT = os.path.join(ROOT, 'LEMMATIZED_WORDS_TEXT.txt')
FINAL_WORDS_SENTENCE_TEXT = os.path.join(ROOT, 'FINAL_WORDS_SENTENCE_TEXT.txt')

CONSOLIDATED_RAW_TEXT = os.path.join(ROOT, 'MEDLINE_CONSOLIDATED_RAW_TEXT.txt')
CONSOLIDATED_SENTENCE_TEXT = os.path.join(ROOT, 'MEDLINE_CONSOLIDATED_SENTENCE_TEXT.txt')
CONSOLIDATED_WORDS_TEXT = os.path.join(ROOT, 'MEDLINE_CONSOLIDATED_WORDS_TEXT.txt')
CONSOLIDATED_PROCSESED_SENTENCE_TEXT = os.path.join(ROOT, 'MEDLINE_PROCSESED_SENTENCE_TEXT.txt')
LEMMATIZED_WORDS_TEXT = os.path.join(ROOT, 'MEDLINE_LEMMATIZED_WORDS_TEXT.txt')
FINAL_WORDS_SENTENCE_TEXT = os.path.join(ROOT, 'MEDLINE_FINAL_WORDS_SENTENCE_TEXT.txt')

ENTITIES_PATH = os.path.join(ROOT, 'entities.dat')